#!/bin/sh

lock() {
	i3lock
}

case "$1" in
	lock)
		lock
		;;
	logout)
		i3-msg exit
		;;
	suspend)
		lock && systemctl suspend
		;;
	reboot)
		echo "Rebooting ..."
		reboot
		;;
	shutdown)
		echo "Shutting down..."
		shutdown now
		;;
	*)
		echo "Usage: $0 {lock|logout|suspend|reboot|shutdown}"
		exit 2
esac

exit 0
